ALTER TABLE "public"."PosCloseout"
  ADD COLUMN "openingCash" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "cashSales" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "cashExpenses" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "cashExpenseItems" TEXT NOT NULL DEFAULT '[]',
  ADD COLUMN "expectedClosingCash" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "closingCash" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "cashVariance" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "public"."PosCloseout" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE "public"."PosCloseout" FROM anon, authenticated;
